site_name: FlowerCare Python Library
site_description: A comprehensive Python library for FlowerCare Bluetooth plant sensors
site_author: Ilya Redkolis
site_url: https://your-docs-site.com

repo_url: https://github.com/eljhr9/growify-core
repo_name: growify-core

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light-green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Steps: getting-started/first-steps.md
  - User Guide:
    - Device Discovery: user-guide/device-discovery.md
    - Reading Sensor Data: user-guide/reading-data.md
    - Historical Data: user-guide/historical-data.md
    - Device Management: user-guide/device-management.md
    - Error Handling: user-guide/error-handling.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Continuous Monitoring: examples/continuous-monitoring.md
    - Multiple Devices: examples/multiple-devices.md
    - Data Export: examples/data-export.md
  - API Reference:
    - FlowerCareDevice: api/device.md
    - FlowerCareScanner: api/scanner.md
    - Data Models: api/models.md
    - Exceptions: api/exceptions.md
  - Advanced:
    - Protocol Details: advanced/protocol.md
    - Performance Tips: advanced/performance.md
    - Extending the Library: advanced/extending.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md